## 파이썬 random 함수

In [14]:
# 파이썬 random 함수
import random

random.random() # -.0(포함)부터 1.0(불포함) 사이의 수
random.randint(1,10) # 1~10(포함) 사이의 정수 중에서 난수 
random.uniform(10,20) # min, max 사이의 float
random.randrange(10) # 지정범위의 int 
random.choice([1,2,3,4,5]) # 리스트 내부에 있는 요소를 랜덤하게 선택
li = [1,2,3,4,5]
random.sample(li,5) # 리스트 요소를 중복 안되게 리턴 - 리스트에 반영 x
random.shuffle(li) # 리스트 요소를 다시 섞어서 리턴 - 리스트에 반영
print(li)

[4, 1, 5, 2, 3]


## numpy의 np.random

In [ ]:
# numpy의 np.random
# rand: 0.0 ~ 1.0 사이의 균일 분포
# randn: 가우시안 표준 정규 분호
# randint: 균일 분포의 정수 난수

In [15]:
# 0.0 ~ 1.0 사이의 균일 분포인 실수
import numpy as np
np.random.seed(0)
print(np.random.rand(5), '\n')
print(np.random.rand(3,2))

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ] 

[[0.64589411 0.43758721]
 [0.891773   0.96366276]
 [0.38344152 0.79172504]]


In [16]:
print(np.random.randint(5),'\n') # 0~4까지 정수 난수 1개
print(np.random.randint(1,20),'\n') # 1~19까지 정수 난수 1개
print(np.random.randint(10, size=10),'\n') # 0~9 정수 난수 10개
print(np.random.randint(10,20, size=5),'\n') # 10~19 정수 난수 5개
print(np.random.randint(10,20, size=(3,5)),'\n') # 10~19 정수난수 (3,5) 

0 

18 

[5 9 8 9 4 3 0 3 5 0] 

[12 13 18 11 13] 

[[13 13 17 10 11]
 [19 19 10 14 17]
 [13 12 17 12 10]] 



In [19]:
print(np.random.choice([1,2,3,4,5]),'\n') # 하나
print(np.random.choice(5,5,replace=False),'\n') # 0~5 정수 5개 중복 안되게
print(np.random.choice(5,5)) # replace=True, 0~5 정수 5개 중복 허용

5 

[3 2 1 4 0] 

[4 1 2 2 0]


In [20]:
li = [0,1,2,3,4]
np.random.shuffle(li)
li

[0, 2, 3, 4, 1]

In [21]:
print(np.random.randn(6),'\n')
print(np.random.randn(3,2))

[ 1.23029068  1.20237985 -0.38732682 -0.30230275 -1.04855297 -1.42001794] 

[[-1.70627019  1.9507754 ]
 [-0.50965218 -0.4380743 ]
 [-1.25279536  0.77749036]]


In [22]:
# 범위내 실수 출력
print(np.random.uniform(1,2,3),'\n') # 1~2 사이의 실수 3개
print(np.random.uniform(0,1,(2,3))) # 0~1 사이의 실수 (2,3) 형태로 출력

[1.46631077 1.24442559 1.15896958] 

[[0.11037514 0.65632959 0.13818295]
 [0.19658236 0.36872517 0.82099323]]


In [23]:
# random_sample은 uniform 하수의 최소값, 최대값을 각각 0,1로 지정한 것과 같음
np.random.random_sample((2,3))
# np.random.uniform(0,1,(2,3)) 이랑 같음

array([[0.09710128, 0.83794491, 0.09609841],
       [0.97645947, 0.4686512 , 0.97676109]])

## 과제

##### Q. 고객 구매데이터 생성(id, 성별, 연령, 지역, 상품, 가격, 구매시간) 하고 데이터 프레임으로 변환한 후 아래 사항을 수행하세요.

##### 구매 데이터 생성
- id : 1번 ~ 1000번 일련번호(관측치 1000개)
- gender : 0,1 정수 난수 생성
- age : 10 ~ 80사이 정수 난수를 생성하고 범주화하여 age_cat 파생
- region : 1 ~ 10 사이 정수 난수 생성
- product : 1개 제품 이상
- price_avg_19 : 1000 ~ 50000 사이 실수 난수 생성하고 범주화하여 price_avg_cat 파생
- price_avg_20 : 1000 ~ 50000 사이 실수 난수 생성하고 범주화하여 price_avg_cat 파생
- qty_19 : 1 ~ 100 사이 정수 난수 생성하여('19년 구매 수량)
- qty_20 : 1 ~ 100 사이 정수 난수 생성하여('20년 구매 수량)
- time_19 : 01 ~ 24 사이 정수 난수 생성하고 오전, 오후, 야간 으로 범주화하여 - time_cat_19 파생('19년에 가장 자주 구매한 시간대)
- time_20 : 01 ~ 24 사이 정수 난수 생성하고 오전, 오후, 야간 으로 범주화하여 - time_cat 파생('20년에 가장 자주 구매한 시간대)
- 구매액은 price * qty로 산출('19년, '20년 각각 계산)하여 pur_19, pur_20 컬럼으로 생성
- 종속변수(결과변수)는 (pur_20 - pur_19)으로 계산하여 구매액 증감을 0(감소), 1(증가)로 범주화하여 pur_gap 컬럼 생성
np.nan으로 각 컬럼별로 10개씩 null값을 삽입하고 각 칼럼의 특성을 고려한 null 값 처리
##### 인사이트 도출
- 통계적 분석 및 시각화하여 탐색한 후 불필요한 컬럼은 삭제하고 필요시 추가 파생변수 생성한 후 분석용 데이터셋을 작성하고 인사이트 3개 이상 도출
- 인사이트 도출하지 못한 경우 데이터를 수정하여 다시 탐색한 후 인사이트 도출 및 기술
##### 데이터 수정시 참조
- 구매액 증감에 영향을 주는 주요 요인과 관련된 인사이트를 만들 수 있는 데이터로 변경하는 점에 중점을 둠
- 구매 감소한 고객의 특성으로 성별, 지역, 선호제픔, 선호 구매시간대, 평균 구매가 level(저가, 중가, 고가)별로 데이터 수정
- 연령, 성별로 상품유형, 구매단가, 구매시간대 등을 복합적으로 그룹화하여 데이터 특성 부여
- 연도별로 상기한 사항들의 변동과 구매 감소간의 상관성을 부여하는 데이터 수정
- 데이터 수정은 불린 인덱싱으로 특정 그룹을 선택한 후 고객 특성에 맞는 값으로 변경